### ISSUE TITLE
It's not possible to specify sandbox mode and debugging level based on environment

### ISSUE THREAD

**Issue by LucaGallinari** [Sylius/PayPalPlugin#178]
We cannot do something like this
```
sylius_pay_pal:
    logging:
        increased: '%env(bool:SYLIUS_PAY_PAL_PLUGIN_LOGGING_INCREASED)%'
    sandbox: '%env(SYLIUS_PAY_PAL_PLUGIN_SANDBOX)%'
```
cause these configs are loaded in a Dependency Injection Extension class.

The only way to do this actually is through a custom compiler pass that replicate what is done in the SyliusPayPalExtension but by reading the env variables.

This is useful in a staging environment that usually should be identical to production, so APP_ENV=prod, but with some custom env variables, like sandbox mode for payments.
