### ISSUE TITLE
[Bug] Symfony %env% not working

### ISSUE THREAD

**Issue by migo315** [Sylius/PayPalPlugin#353]
**SyliusPayPalPlugin version affected**: ^1.6

**Description**  
In a Symfony application, it is common to set configurations via parameters. And Symfony also offers the %env()% syntax to set configurations based on the environment variables. But unfortunately this does not work in this plugin because the extension processes the configuration “incorrectly”.

Both here https://github.com/Sylius/PayPalPlugin/blob/1.6/src/DependencyInjection/SyliusPayPalExtension.php#L37 and here https://github.com/Sylius/PayPalPlugin/blob/1.6/src/DependencyInjection/SyliusPayPalExtension.php#L39 the content of the $config is used directly to manupulate the DI. 

But if I use %env()%, the value of the environment variable has not yet been processed here. 

This means that I cannot activate or deactivate the sandbox mode via environment variables. And I cannot configure the sandbox mode dynamically in any other way.

Ironically, I can change the other credentials such as client ID dynamically, but not sandbox mode (and logging). 

**Steps to reproduce**  
- Add Environemt Variabel "PAYPAL_SANDBOX_ENABLED" with value "true"
- Use following config in paypal.yaml:
```
parameters:
  paypal_sandbox_enabled: '%env(bool:PAYPAL_SANDBOX_ENABLED)%'
  paypal_logging_increased: '%env(bool:PAYPAL_SANDBOX_ENABLED)%'

sylius_pay_pal:
  sandbox: '%paypal_sandbox_enabled%'
  logging:
    increased: '%paypal_logging_increased%'
```
- Add `dd($config['sandbox'])` in SyliusPayPalExtension
- Output would not be "true", it would be something like `env_f46406f893ee5143_bool_PAYPAL_SANDBOX_ENABLED_d40e533fc33426dce6c68c22141a10b6 `
- And that would always evaluate to true

**Possible Solution**  
- Move sandbox mode to database like the other credentials
- Or do not manipulate the DI with the configuration at compile time. Instead, create and use a service, pass the configuration to the service and determine the base URL at runtime

The requirement may seem “unimportant”. But in larger projects with multiple environments, it is important that a stage and a production system run with the same code and that only credentials that are normally passed via environment variables are changed. In this specific case, I have difficulties running the stage in the sandbox and the production in live mode with the same code.
